/*
 * generated by Xtext 2.12.0
 */
package org.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import tripModelXtext.ui.internal.TripModelXtextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TripModelLanguageTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TripModelXtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TripModelXtextActivator.getInstance().getInjector(TripModelXtextActivator.ORG_TRIPMODELLANGUAGETEXT);
	}
	
}
