/*
 * generated by Xtext 2.12.0
 */
package org.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.parser.antlr.internal.InternalTripModelLanguageTextParser;
import org.services.TripModelLanguageTextGrammarAccess;

public class TripModelLanguageTextParser extends AbstractAntlrParser {

	@Inject
	private TripModelLanguageTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTripModelLanguageTextParser createParser(XtextTokenStream stream) {
		return new InternalTripModelLanguageTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TripModel";
	}

	public TripModelLanguageTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TripModelLanguageTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
