/**
 * generated by Xtext 2.12.0
 */
package org.ui.contentassist;

import org.ui.contentassist.AbstractTripModelLanguageTextProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TripModelLanguageTextProposalProvider extends AbstractTripModelLanguageTextProposalProvider {
}
