/*
 * generated by Xtext 2.12.0
 */
package org.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tripModelXtext.ui.internal.TripModelXtextActivator;

public class TripModelLanguageTextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TripModelXtextActivator.getInstance().getInjector("org.TripModelLanguageText");
	}

}
