/**
 * generated by Xtext 2.12.0
 */
package org.ide;

import org.ide.AbstractTripModelLanguageTextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TripModelLanguageTextIdeModule extends AbstractTripModelLanguageTextIdeModule {
}
