/*
 * generated by Xtext 2.12.0
 */
package org.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TripModelLanguageTextGrammarAccess extends AbstractGrammarElementFinder {
	
	public class TripModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.TripModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTripModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTripModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTripKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cTripAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cTripTripParserRuleCall_3_2_0 = (RuleCall)cTripAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cTripAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cTripTripParserRuleCall_3_3_1_0 = (RuleCall)cTripAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLocationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLocationAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cLocationLocationParserRuleCall_4_2_0 = (RuleCall)cLocationAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cLocationAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cLocationLocationParserRuleCall_4_3_1_0 = (RuleCall)cLocationAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//TripModel:
		//	{TripModel}
		//	'TripModel'
		//	'{' ('trip' '{' trip+=Trip ("," trip+=Trip)* '}')? ('location' '{' location+=location ("," location+=location)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{TripModel} 'TripModel' '{' ('trip' '{' trip+=Trip ("," trip+=Trip)* '}')? ('location' '{' location+=location (","
		//location+=location)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{TripModel}
		public Action getTripModelAction_0() { return cTripModelAction_0; }
		
		//'TripModel'
		public Keyword getTripModelKeyword_1() { return cTripModelKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('trip' '{' trip+=Trip ("," trip+=Trip)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'trip'
		public Keyword getTripKeyword_3_0() { return cTripKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//trip+=Trip
		public Assignment getTripAssignment_3_2() { return cTripAssignment_3_2; }
		
		//Trip
		public RuleCall getTripTripParserRuleCall_3_2_0() { return cTripTripParserRuleCall_3_2_0; }
		
		//("," trip+=Trip)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//trip+=Trip
		public Assignment getTripAssignment_3_3_1() { return cTripAssignment_3_3_1; }
		
		//Trip
		public RuleCall getTripTripParserRuleCall_3_3_1_0() { return cTripTripParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('location' '{' location+=location ("," location+=location)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'location'
		public Keyword getLocationKeyword_4_0() { return cLocationKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//location+=location
		public Assignment getLocationAssignment_4_2() { return cLocationAssignment_4_2; }
		
		//location
		public RuleCall getLocationLocationParserRuleCall_4_2_0() { return cLocationLocationParserRuleCall_4_2_0; }
		
		//("," location+=location)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//location+=location
		public Assignment getLocationAssignment_4_3_1() { return cLocationAssignment_4_3_1; }
		
		//location
		public RuleCall getLocationLocationParserRuleCall_4_3_1_0() { return cLocationLocationParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.Service");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cService_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOtherServiceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTravelServiceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Service:
		//	Service_Impl | OtherService | TravelService;
		@Override public ParserRule getRule() { return rule; }
		
		//Service_Impl | OtherService | TravelService
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Service_Impl
		public RuleCall getService_ImplParserRuleCall_0() { return cService_ImplParserRuleCall_0; }
		
		//OtherService
		public RuleCall getOtherServiceParserRuleCall_1() { return cOtherServiceParserRuleCall_1; }
		
		//TravelService
		public RuleCall getTravelServiceParserRuleCall_2() { return cTravelServiceParserRuleCall_2; }
	}
	public class TripElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.Trip");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTripKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEndKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cEndAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cEndEDateParserRuleCall_3_1_0 = (RuleCall)cEndAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStartKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStartAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStartEDateParserRuleCall_4_1_0 = (RuleCall)cStartAssignment_4_1.eContents().get(0);
		private final Keyword cSourceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSourceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSourceLocationCrossReference_6_0 = (CrossReference)cSourceAssignment_6.eContents().get(0);
		private final RuleCall cSourceLocationEStringParserRuleCall_6_0_1 = (RuleCall)cSourceLocationCrossReference_6_0.eContents().get(1);
		private final Keyword cDestinationKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDestinationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cDestinationLocationCrossReference_8_0 = (CrossReference)cDestinationAssignment_8.eContents().get(0);
		private final RuleCall cDestinationLocationEStringParserRuleCall_8_0_1 = (RuleCall)cDestinationLocationCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cServiceKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cServiceAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cServiceServiceParserRuleCall_9_2_0 = (RuleCall)cServiceAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cServiceAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cServiceServiceParserRuleCall_9_3_1_0 = (RuleCall)cServiceAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Trip:
		//	'Trip'
		//	name=EString
		//	'{' ('End' End=EDate)? ('Start' Start=EDate)?
		//	'source' source=[location|EString]
		//	'destination' destination=[location|EString] ('service' '{' service+=Service ("," service+=Service)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Trip' name=EString '{' ('End' End=EDate)? ('Start' Start=EDate)? 'source' source=[location|EString] 'destination'
		//destination=[location|EString] ('service' '{' service+=Service ("," service+=Service)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Trip'
		public Keyword getTripKeyword_0() { return cTripKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('End' End=EDate)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'End'
		public Keyword getEndKeyword_3_0() { return cEndKeyword_3_0; }
		
		//End=EDate
		public Assignment getEndAssignment_3_1() { return cEndAssignment_3_1; }
		
		//EDate
		public RuleCall getEndEDateParserRuleCall_3_1_0() { return cEndEDateParserRuleCall_3_1_0; }
		
		//('Start' Start=EDate)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Start'
		public Keyword getStartKeyword_4_0() { return cStartKeyword_4_0; }
		
		//Start=EDate
		public Assignment getStartAssignment_4_1() { return cStartAssignment_4_1; }
		
		//EDate
		public RuleCall getStartEDateParserRuleCall_4_1_0() { return cStartEDateParserRuleCall_4_1_0; }
		
		//'source'
		public Keyword getSourceKeyword_5() { return cSourceKeyword_5; }
		
		//source=[location|EString]
		public Assignment getSourceAssignment_6() { return cSourceAssignment_6; }
		
		//[location|EString]
		public CrossReference getSourceLocationCrossReference_6_0() { return cSourceLocationCrossReference_6_0; }
		
		//EString
		public RuleCall getSourceLocationEStringParserRuleCall_6_0_1() { return cSourceLocationEStringParserRuleCall_6_0_1; }
		
		//'destination'
		public Keyword getDestinationKeyword_7() { return cDestinationKeyword_7; }
		
		//destination=[location|EString]
		public Assignment getDestinationAssignment_8() { return cDestinationAssignment_8; }
		
		//[location|EString]
		public CrossReference getDestinationLocationCrossReference_8_0() { return cDestinationLocationCrossReference_8_0; }
		
		//EString
		public RuleCall getDestinationLocationEStringParserRuleCall_8_0_1() { return cDestinationLocationEStringParserRuleCall_8_0_1; }
		
		//('service' '{' service+=Service ("," service+=Service)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'service'
		public Keyword getServiceKeyword_9_0() { return cServiceKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//service+=Service
		public Assignment getServiceAssignment_9_2() { return cServiceAssignment_9_2; }
		
		//Service
		public RuleCall getServiceServiceParserRuleCall_9_2_0() { return cServiceServiceParserRuleCall_9_2_0; }
		
		//("," service+=Service)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//service+=Service
		public Assignment getServiceAssignment_9_3_1() { return cServiceAssignment_9_3_1; }
		
		//Service
		public RuleCall getServiceServiceParserRuleCall_9_3_1_0() { return cServiceServiceParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLocationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLocationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//location:
		//	{location}
		//	'location'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{location} 'location' name=EString
		public Group getGroup() { return cGroup; }
		
		//{location}
		public Action getLocationAction_0() { return cLocationAction_0; }
		
		//'location'
		public Keyword getLocationKeyword_1() { return cLocationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class Service_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.Service_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cServiceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCostKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCostAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCostEFloatParserRuleCall_4_1_0 = (RuleCall)cCostAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDurationKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDurationAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_5_1_0 = (RuleCall)cDurationAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRatingKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRatingAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRatingEIntParserRuleCall_6_1_0 = (RuleCall)cRatingAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTypeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTypeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_7_1_0 = (RuleCall)cTypeAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Service_Impl Service:
		//	{Service}
		//	'Service'
		//	name=EString
		//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Service} 'Service' name=EString '{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type'
		//Type=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Service}
		public Action getServiceAction_0() { return cServiceAction_0; }
		
		//'Service'
		public Keyword getServiceKeyword_1() { return cServiceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('Cost' Cost=EFloat)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Cost'
		public Keyword getCostKeyword_4_0() { return cCostKeyword_4_0; }
		
		//Cost=EFloat
		public Assignment getCostAssignment_4_1() { return cCostAssignment_4_1; }
		
		//EFloat
		public RuleCall getCostEFloatParserRuleCall_4_1_0() { return cCostEFloatParserRuleCall_4_1_0; }
		
		//('Duration' Duration=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Duration'
		public Keyword getDurationKeyword_5_0() { return cDurationKeyword_5_0; }
		
		//Duration=EInt
		public Assignment getDurationAssignment_5_1() { return cDurationAssignment_5_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_5_1_0() { return cDurationEIntParserRuleCall_5_1_0; }
		
		//('Rating' Rating=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'Rating'
		public Keyword getRatingKeyword_6_0() { return cRatingKeyword_6_0; }
		
		//Rating=EInt
		public Assignment getRatingAssignment_6_1() { return cRatingAssignment_6_1; }
		
		//EInt
		public RuleCall getRatingEIntParserRuleCall_6_1_0() { return cRatingEIntParserRuleCall_6_1_0; }
		
		//('Type' Type=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'Type'
		public Keyword getTypeKeyword_7_0() { return cTypeKeyword_7_0; }
		
		//Type=EString
		public Assignment getTypeAssignment_7_1() { return cTypeAssignment_7_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_7_1_0() { return cTypeEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.EDate");
		private final RuleCall cDATETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EDate ecore::EDate:
		//	DATE /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//DATE
		public RuleCall getDATETerminalRuleCall() { return cDATETerminalRuleCall; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat ecore::EFloat:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class OtherServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.OtherService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOtherServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCostKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCostAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCostEFloatParserRuleCall_3_1_0 = (RuleCall)cCostAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDurationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDurationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_4_1_0 = (RuleCall)cDurationAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRatingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRatingAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRatingEIntParserRuleCall_5_1_0 = (RuleCall)cRatingAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Keyword cLocationKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLocationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cLocationLocationCrossReference_8_0 = (CrossReference)cLocationAssignment_8.eContents().get(0);
		private final RuleCall cLocationLocationEStringParserRuleCall_8_0_1 = (RuleCall)cLocationLocationCrossReference_8_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//OtherService:
		//	'OtherService'
		//	name=EString
		//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
		//	'location' location=[location|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'OtherService' name=EString '{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type'
		//Type=EString)? 'location' location=[location|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'OtherService'
		public Keyword getOtherServiceKeyword_0() { return cOtherServiceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('Cost' Cost=EFloat)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Cost'
		public Keyword getCostKeyword_3_0() { return cCostKeyword_3_0; }
		
		//Cost=EFloat
		public Assignment getCostAssignment_3_1() { return cCostAssignment_3_1; }
		
		//EFloat
		public RuleCall getCostEFloatParserRuleCall_3_1_0() { return cCostEFloatParserRuleCall_3_1_0; }
		
		//('Duration' Duration=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Duration'
		public Keyword getDurationKeyword_4_0() { return cDurationKeyword_4_0; }
		
		//Duration=EInt
		public Assignment getDurationAssignment_4_1() { return cDurationAssignment_4_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_4_1_0() { return cDurationEIntParserRuleCall_4_1_0; }
		
		//('Rating' Rating=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Rating'
		public Keyword getRatingKeyword_5_0() { return cRatingKeyword_5_0; }
		
		//Rating=EInt
		public Assignment getRatingAssignment_5_1() { return cRatingAssignment_5_1; }
		
		//EInt
		public RuleCall getRatingEIntParserRuleCall_5_1_0() { return cRatingEIntParserRuleCall_5_1_0; }
		
		//('Type' Type=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'Type'
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }
		
		//Type=EString
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_6_1_0() { return cTypeEStringParserRuleCall_6_1_0; }
		
		//'location'
		public Keyword getLocationKeyword_7() { return cLocationKeyword_7; }
		
		//location=[location|EString]
		public Assignment getLocationAssignment_8() { return cLocationAssignment_8; }
		
		//[location|EString]
		public CrossReference getLocationLocationCrossReference_8_0() { return cLocationLocationCrossReference_8_0; }
		
		//EString
		public RuleCall getLocationLocationEStringParserRuleCall_8_0_1() { return cLocationLocationEStringParserRuleCall_8_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class TravelServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.TravelService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTravelServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCostKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCostAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCostEFloatParserRuleCall_3_1_0 = (RuleCall)cCostAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDurationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDurationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_4_1_0 = (RuleCall)cDurationAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRatingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRatingAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRatingEIntParserRuleCall_5_1_0 = (RuleCall)cRatingAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Keyword cSourceKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSourceAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cSourceLocationCrossReference_8_0 = (CrossReference)cSourceAssignment_8.eContents().get(0);
		private final RuleCall cSourceLocationEStringParserRuleCall_8_0_1 = (RuleCall)cSourceLocationCrossReference_8_0.eContents().get(1);
		private final Keyword cDestinationKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDestinationAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cDestinationLocationCrossReference_10_0 = (CrossReference)cDestinationAssignment_10.eContents().get(0);
		private final RuleCall cDestinationLocationEStringParserRuleCall_10_0_1 = (RuleCall)cDestinationLocationCrossReference_10_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//TravelService:
		//	'TravelService'
		//	name=EString
		//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
		//	'source' source=[location|EString]
		//	'destination' destination=[location|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TravelService' name=EString '{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type'
		//Type=EString)? 'source' source=[location|EString] 'destination' destination=[location|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'TravelService'
		public Keyword getTravelServiceKeyword_0() { return cTravelServiceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('Cost' Cost=EFloat)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Cost'
		public Keyword getCostKeyword_3_0() { return cCostKeyword_3_0; }
		
		//Cost=EFloat
		public Assignment getCostAssignment_3_1() { return cCostAssignment_3_1; }
		
		//EFloat
		public RuleCall getCostEFloatParserRuleCall_3_1_0() { return cCostEFloatParserRuleCall_3_1_0; }
		
		//('Duration' Duration=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Duration'
		public Keyword getDurationKeyword_4_0() { return cDurationKeyword_4_0; }
		
		//Duration=EInt
		public Assignment getDurationAssignment_4_1() { return cDurationAssignment_4_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_4_1_0() { return cDurationEIntParserRuleCall_4_1_0; }
		
		//('Rating' Rating=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Rating'
		public Keyword getRatingKeyword_5_0() { return cRatingKeyword_5_0; }
		
		//Rating=EInt
		public Assignment getRatingAssignment_5_1() { return cRatingAssignment_5_1; }
		
		//EInt
		public RuleCall getRatingEIntParserRuleCall_5_1_0() { return cRatingEIntParserRuleCall_5_1_0; }
		
		//('Type' Type=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'Type'
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }
		
		//Type=EString
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_6_1_0() { return cTypeEStringParserRuleCall_6_1_0; }
		
		//'source'
		public Keyword getSourceKeyword_7() { return cSourceKeyword_7; }
		
		//source=[location|EString]
		public Assignment getSourceAssignment_8() { return cSourceAssignment_8; }
		
		//[location|EString]
		public CrossReference getSourceLocationCrossReference_8_0() { return cSourceLocationCrossReference_8_0; }
		
		//EString
		public RuleCall getSourceLocationEStringParserRuleCall_8_0_1() { return cSourceLocationEStringParserRuleCall_8_0_1; }
		
		//'destination'
		public Keyword getDestinationKeyword_9() { return cDestinationKeyword_9; }
		
		//destination=[location|EString]
		public Assignment getDestinationAssignment_10() { return cDestinationAssignment_10; }
		
		//[location|EString]
		public CrossReference getDestinationLocationCrossReference_10_0() { return cDestinationLocationCrossReference_10_0; }
		
		//EString
		public RuleCall getDestinationLocationEStringParserRuleCall_10_0_1() { return cDestinationLocationEStringParserRuleCall_10_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	
	
	private final TripModelElements pTripModel;
	private final ServiceElements pService;
	private final TripElements pTrip;
	private final LocationElements pLocation;
	private final Service_ImplElements pService_Impl;
	private final EDateElements pEDate;
	private final TerminalRule tDATE;
	private final EStringElements pEString;
	private final EFloatElements pEFloat;
	private final EIntElements pEInt;
	private final OtherServiceElements pOtherService;
	private final TravelServiceElements pTravelService;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TripModelLanguageTextGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTripModel = new TripModelElements();
		this.pService = new ServiceElements();
		this.pTrip = new TripElements();
		this.pLocation = new LocationElements();
		this.pService_Impl = new Service_ImplElements();
		this.pEDate = new EDateElements();
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.TripModelLanguageText.DATE");
		this.pEString = new EStringElements();
		this.pEFloat = new EFloatElements();
		this.pEInt = new EIntElements();
		this.pOtherService = new OtherServiceElements();
		this.pTravelService = new TravelServiceElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.TripModelLanguageText".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TripModel:
	//	{TripModel}
	//	'TripModel'
	//	'{' ('trip' '{' trip+=Trip ("," trip+=Trip)* '}')? ('location' '{' location+=location ("," location+=location)* '}')?
	//	'}';
	public TripModelElements getTripModelAccess() {
		return pTripModel;
	}
	
	public ParserRule getTripModelRule() {
		return getTripModelAccess().getRule();
	}
	
	//Service:
	//	Service_Impl | OtherService | TravelService;
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//Trip:
	//	'Trip'
	//	name=EString
	//	'{' ('End' End=EDate)? ('Start' Start=EDate)?
	//	'source' source=[location|EString]
	//	'destination' destination=[location|EString] ('service' '{' service+=Service ("," service+=Service)* '}')?
	//	'}';
	public TripElements getTripAccess() {
		return pTrip;
	}
	
	public ParserRule getTripRule() {
		return getTripAccess().getRule();
	}
	
	//location:
	//	{location}
	//	'location'
	//	name=EString;
	public LocationElements getLocationAccess() {
		return pLocation;
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}
	
	//Service_Impl Service:
	//	{Service}
	//	'Service'
	//	name=EString
	//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
	//	'}';
	public Service_ImplElements getService_ImplAccess() {
		return pService_Impl;
	}
	
	public ParserRule getService_ImplRule() {
		return getService_ImplAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	DATE /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//terminal DATE:
	//	'0'..'9'* '-' '0'..'9'* '-' '0'..'9'*;
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//OtherService:
	//	'OtherService'
	//	name=EString
	//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
	//	'location' location=[location|EString]
	//	'}';
	public OtherServiceElements getOtherServiceAccess() {
		return pOtherService;
	}
	
	public ParserRule getOtherServiceRule() {
		return getOtherServiceAccess().getRule();
	}
	
	//TravelService:
	//	'TravelService'
	//	name=EString
	//	'{' ('Cost' Cost=EFloat)? ('Duration' Duration=EInt)? ('Rating' Rating=EInt)? ('Type' Type=EString)?
	//	'source' source=[location|EString]
	//	'destination' destination=[location|EString]
	//	'}';
	public TravelServiceElements getTravelServiceAccess() {
		return pTravelService;
	}
	
	public ParserRule getTravelServiceRule() {
		return getTravelServiceAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
