/**
 * generated by Xtext 2.12.0
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.ui.AbstractTripModelLanguageTextUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TripModelLanguageTextUiModule extends AbstractTripModelLanguageTextUiModule {
  public TripModelLanguageTextUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
