/**
 * generated by Xtext 2.12.0
 */
package org.validation;

import org.validation.AbstractTripModelLanguageTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TripModelLanguageTextValidator extends AbstractTripModelLanguageTextValidator {
}
