/**
 * generated by Xtext 2.12.0
 */
package org;

import org.TripModelLanguageTextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TripModelLanguageTextStandaloneSetup extends TripModelLanguageTextStandaloneSetupGenerated {
  public static void doSetup() {
    new TripModelLanguageTextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
