/**
 * generated by Xtext 2.12.0
 */
package org;

import org.AbstractTripModelLanguageTextRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TripModelLanguageTextRuntimeModule extends AbstractTripModelLanguageTextRuntimeModule {
}
