/*
 * generated by Xtext 2.12.0
 */
package org.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.ide.contentassist.antlr.internal.InternalTripModelLanguageTextParser;
import org.services.TripModelLanguageTextGrammarAccess;

public class TripModelLanguageTextParser extends AbstractContentAssistParser {

	@Inject
	private TripModelLanguageTextGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalTripModelLanguageTextParser createParser() {
		InternalTripModelLanguageTextParser result = new InternalTripModelLanguageTextParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getServiceAccess().getAlternatives(), "rule__Service__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getTripModelAccess().getGroup(), "rule__TripModel__Group__0");
					put(grammarAccess.getTripModelAccess().getGroup_3(), "rule__TripModel__Group_3__0");
					put(grammarAccess.getTripModelAccess().getGroup_3_3(), "rule__TripModel__Group_3_3__0");
					put(grammarAccess.getTripModelAccess().getGroup_4(), "rule__TripModel__Group_4__0");
					put(grammarAccess.getTripModelAccess().getGroup_4_3(), "rule__TripModel__Group_4_3__0");
					put(grammarAccess.getTripAccess().getGroup(), "rule__Trip__Group__0");
					put(grammarAccess.getTripAccess().getGroup_3(), "rule__Trip__Group_3__0");
					put(grammarAccess.getTripAccess().getGroup_4(), "rule__Trip__Group_4__0");
					put(grammarAccess.getTripAccess().getGroup_9(), "rule__Trip__Group_9__0");
					put(grammarAccess.getTripAccess().getGroup_9_3(), "rule__Trip__Group_9_3__0");
					put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
					put(grammarAccess.getService_ImplAccess().getGroup(), "rule__Service_Impl__Group__0");
					put(grammarAccess.getService_ImplAccess().getGroup_4(), "rule__Service_Impl__Group_4__0");
					put(grammarAccess.getService_ImplAccess().getGroup_5(), "rule__Service_Impl__Group_5__0");
					put(grammarAccess.getService_ImplAccess().getGroup_6(), "rule__Service_Impl__Group_6__0");
					put(grammarAccess.getService_ImplAccess().getGroup_7(), "rule__Service_Impl__Group_7__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getOtherServiceAccess().getGroup(), "rule__OtherService__Group__0");
					put(grammarAccess.getOtherServiceAccess().getGroup_3(), "rule__OtherService__Group_3__0");
					put(grammarAccess.getOtherServiceAccess().getGroup_4(), "rule__OtherService__Group_4__0");
					put(grammarAccess.getOtherServiceAccess().getGroup_5(), "rule__OtherService__Group_5__0");
					put(grammarAccess.getOtherServiceAccess().getGroup_6(), "rule__OtherService__Group_6__0");
					put(grammarAccess.getTravelServiceAccess().getGroup(), "rule__TravelService__Group__0");
					put(grammarAccess.getTravelServiceAccess().getGroup_3(), "rule__TravelService__Group_3__0");
					put(grammarAccess.getTravelServiceAccess().getGroup_4(), "rule__TravelService__Group_4__0");
					put(grammarAccess.getTravelServiceAccess().getGroup_5(), "rule__TravelService__Group_5__0");
					put(grammarAccess.getTravelServiceAccess().getGroup_6(), "rule__TravelService__Group_6__0");
					put(grammarAccess.getTripModelAccess().getTripAssignment_3_2(), "rule__TripModel__TripAssignment_3_2");
					put(grammarAccess.getTripModelAccess().getTripAssignment_3_3_1(), "rule__TripModel__TripAssignment_3_3_1");
					put(grammarAccess.getTripModelAccess().getLocationAssignment_4_2(), "rule__TripModel__LocationAssignment_4_2");
					put(grammarAccess.getTripModelAccess().getLocationAssignment_4_3_1(), "rule__TripModel__LocationAssignment_4_3_1");
					put(grammarAccess.getTripAccess().getNameAssignment_1(), "rule__Trip__NameAssignment_1");
					put(grammarAccess.getTripAccess().getEndAssignment_3_1(), "rule__Trip__EndAssignment_3_1");
					put(grammarAccess.getTripAccess().getStartAssignment_4_1(), "rule__Trip__StartAssignment_4_1");
					put(grammarAccess.getTripAccess().getSourceAssignment_6(), "rule__Trip__SourceAssignment_6");
					put(grammarAccess.getTripAccess().getDestinationAssignment_8(), "rule__Trip__DestinationAssignment_8");
					put(grammarAccess.getTripAccess().getServiceAssignment_9_2(), "rule__Trip__ServiceAssignment_9_2");
					put(grammarAccess.getTripAccess().getServiceAssignment_9_3_1(), "rule__Trip__ServiceAssignment_9_3_1");
					put(grammarAccess.getLocationAccess().getNameAssignment_2(), "rule__Location__NameAssignment_2");
					put(grammarAccess.getService_ImplAccess().getNameAssignment_2(), "rule__Service_Impl__NameAssignment_2");
					put(grammarAccess.getService_ImplAccess().getCostAssignment_4_1(), "rule__Service_Impl__CostAssignment_4_1");
					put(grammarAccess.getService_ImplAccess().getDurationAssignment_5_1(), "rule__Service_Impl__DurationAssignment_5_1");
					put(grammarAccess.getService_ImplAccess().getRatingAssignment_6_1(), "rule__Service_Impl__RatingAssignment_6_1");
					put(grammarAccess.getService_ImplAccess().getTypeAssignment_7_1(), "rule__Service_Impl__TypeAssignment_7_1");
					put(grammarAccess.getOtherServiceAccess().getNameAssignment_1(), "rule__OtherService__NameAssignment_1");
					put(grammarAccess.getOtherServiceAccess().getCostAssignment_3_1(), "rule__OtherService__CostAssignment_3_1");
					put(grammarAccess.getOtherServiceAccess().getDurationAssignment_4_1(), "rule__OtherService__DurationAssignment_4_1");
					put(grammarAccess.getOtherServiceAccess().getRatingAssignment_5_1(), "rule__OtherService__RatingAssignment_5_1");
					put(grammarAccess.getOtherServiceAccess().getTypeAssignment_6_1(), "rule__OtherService__TypeAssignment_6_1");
					put(grammarAccess.getOtherServiceAccess().getLocationAssignment_8(), "rule__OtherService__LocationAssignment_8");
					put(grammarAccess.getTravelServiceAccess().getNameAssignment_1(), "rule__TravelService__NameAssignment_1");
					put(grammarAccess.getTravelServiceAccess().getCostAssignment_3_1(), "rule__TravelService__CostAssignment_3_1");
					put(grammarAccess.getTravelServiceAccess().getDurationAssignment_4_1(), "rule__TravelService__DurationAssignment_4_1");
					put(grammarAccess.getTravelServiceAccess().getRatingAssignment_5_1(), "rule__TravelService__RatingAssignment_5_1");
					put(grammarAccess.getTravelServiceAccess().getTypeAssignment_6_1(), "rule__TravelService__TypeAssignment_6_1");
					put(grammarAccess.getTravelServiceAccess().getSourceAssignment_8(), "rule__TravelService__SourceAssignment_8");
					put(grammarAccess.getTravelServiceAccess().getDestinationAssignment_10(), "rule__TravelService__DestinationAssignment_10");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TripModelLanguageTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TripModelLanguageTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
